from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG_DIR = ROOT / "config"
DOCKER_DIR = ROOT / "docker"
MOCK_API_FIXTURES_DIR = DOCKER_DIR / "mock_exchange_api" / "fixtures"
LOG_FILE = DOCKER_DIR / "fixtures" / "payment_gateway.log"
GENERATED_DIR = ROOT / "data" / "generated"


SETTLEMENT_DATE = "2026-04-20"

INTERNAL_PAYOUTS = [
    {
        "payout_id": "PAYOUT-1001",
        "account_id": "ACC001",
        "amount_usd": 1000.0,
        "currency": "USD",
        "settled_at": SETTLEMENT_DATE,
        "status": "settled",
    },
    {
        "payout_id": "PAYOUT-1002",
        "account_id": "ACC002",
        "amount_usd": 2150.25,
        "currency": "EUR",
        "settled_at": SETTLEMENT_DATE,
        "status": "pending_review",
    },
    {
        "payout_id": "PAYOUT-1003",
        "account_id": "ACC003",
        "amount_usd": 780.0,
        "currency": "GBP",
        "settled_at": SETTLEMENT_DATE,
        "status": "settled",
    },
]

EXCHANGE_SETTLEMENTS = [
    {
        "payout_id": "PAYOUT-1001",
        "account_id": "ACC001",
        "exchange_account_id": "EX-001",
        "amount_usd": 1000.0,
        "currency": "USD",
        "status": "settled",
        "exchange_timestamp": "2026-04-20T08:14:58Z",
    },
    {
        "payout_id": "PAYOUT-1002",
        "account_id": "ACC002",
        "exchange_account_id": "EX-002",
        "amount_usd": 2098.75,
        "currency": "EUR",
        "status": "settled",
        "exchange_timestamp": "2026-04-20T08:15:18Z",
    },
    {
        "payout_id": "PAYOUT-1004",
        "account_id": "ACC003",
        "exchange_account_id": "EX-003",
        "amount_usd": 120.0,
        "currency": "GBP",
        "status": "settled",
        "exchange_timestamp": "2026-04-20T09:01:00Z",
    },
]

FX_RATES = {
    "as_of": SETTLEMENT_DATE,
    "base_currency": "USD",
    "rates": {
        "USD": 1.0,
        "EUR": 0.92,
        "GBP": 0.79,
        "INR": 83.45,
    },
    "pairs": [
        {"from_currency": "USD", "to_currency": "USD", "rate": 1.0},
        {"from_currency": "EUR", "to_currency": "USD", "rate": 1.08695652},
        {"from_currency": "GBP", "to_currency": "USD", "rate": 1.26582278},
        {"from_currency": "INR", "to_currency": "USD", "rate": 0.01198322},
    ],
}

ACCOUNT_MAPPING = {
    "generated_for": SETTLEMENT_DATE,
    "mappings": [
        {
            "account_id": "ACC001",
            "exchange_account_id": "EX-001",
            "entity": "Alpha Treasury",
            "base_currency": "USD",
        },
        {
            "account_id": "ACC002",
            "exchange_account_id": "EX-002",
            "entity": "Beta Markets",
            "base_currency": "EUR",
        },
        {
            "account_id": "ACC003",
            "exchange_account_id": "EX-003",
            "entity": "Gamma Ops",
            "base_currency": "GBP",
        },
    ],
}

LOG_LINES = [
    "2026-04-20T08:14:57Z INFO payment-gateway payout_id=PAYOUT-1001 account_id=ACC001 status=settled amount_usd=1000.00 correlation_id=corr-1001",
    "2026-04-20T08:15:02Z INFO payment-gateway payout_id=PAYOUT-1002 account_id=ACC002 status=queued amount_usd=2150.25 correlation_id=corr-1002",
    "2026-04-20T08:15:05Z WARN payment-gateway payout_id=PAYOUT-1002 account_id=ACC002 retry=1 event=webhook_timeout upstream=exchange-api latency_ms=3200 correlation_id=corr-1002",
    "2026-04-20T08:15:11Z WARN payment-gateway payout_id=PAYOUT-1002 account_id=ACC002 retry=2 event=webhook_timeout upstream=exchange-api latency_ms=4805 correlation_id=corr-1002",
    "2026-04-20T08:15:16Z ERROR payment-gateway payout_id=PAYOUT-1002 account_id=ACC002 retry=3 event=retry_storm upstream=exchange-api status=deferred correlation_id=corr-1002",
    "2026-04-20T08:17:03Z INFO payment-gateway payout_id=PAYOUT-1003 account_id=ACC003 status=settled amount_usd=780.00 correlation_id=corr-1003",
]


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def build_seed_sql() -> str:
    statements = [
        "-- Generated by data/generate_mock_data.py",
        "TRUNCATE demo_internal_payouts, demo_exchange_settlements, demo_fx_rates RESTART IDENTITY;",
    ]

    for payout in INTERNAL_PAYOUTS:
        statements.append(
            "INSERT INTO demo_internal_payouts (payout_id, account_id, amount_usd, currency, settled_at, status) "
            f"VALUES ('{payout['payout_id']}', '{payout['account_id']}', {payout['amount_usd']}, '{payout['currency']}', '{payout['settled_at']}', '{payout['status']}');"
        )

    for payout in EXCHANGE_SETTLEMENTS:
        statements.append(
            "INSERT INTO demo_exchange_settlements (payout_id, account_id, amount_usd, currency, settled_at, status, exchange_timestamp) "
            f"VALUES ('{payout['payout_id']}', '{payout['account_id']}', {payout['amount_usd']}, '{payout['currency']}', '{SETTLEMENT_DATE}', '{payout['status']}', '{payout['exchange_timestamp']}');"
        )

    for pair in FX_RATES["pairs"]:
        statements.append(
            "INSERT INTO demo_fx_rates (from_currency, to_currency, rate, rate_date, source) "
            f"VALUES ('{pair['from_currency']}', '{pair['to_currency']}', {pair['rate']}, '{SETTLEMENT_DATE}', 'generator');"
        )

    return "\n".join(statements) + "\n"


def main() -> None:
    write_json(CONFIG_DIR / "fx_rates.json", FX_RATES)
    write_json(CONFIG_DIR / "account_mapping.json", ACCOUNT_MAPPING)
    write_json(
        MOCK_API_FIXTURES_DIR / "settlements.json",
        {"settlement_date": SETTLEMENT_DATE, "records": EXCHANGE_SETTLEMENTS},
    )
    write_json(MOCK_API_FIXTURES_DIR / "accounts.json", {"accounts": {
        item["account_id"]: {
            "exchange_account_id": item["exchange_account_id"],
            "entity": item["entity"],
            "region": "US" if item["account_id"] == "ACC001" else ("EU" if item["account_id"] == "ACC002" else "UK"),
        }
        for item in ACCOUNT_MAPPING["mappings"]
    }})
    write_text(LOG_FILE, "\n".join(LOG_LINES) + "\n")
    write_json(
        GENERATED_DIR / "internal_payouts.json",
        {"settlement_date": SETTLEMENT_DATE, "records": INTERNAL_PAYOUTS},
    )
    write_text(GENERATED_DIR / "seed_demo_data.sql", build_seed_sql())

    print("Generated mock data artifacts:")
    print(f"- {CONFIG_DIR / 'fx_rates.json'}")
    print(f"- {CONFIG_DIR / 'account_mapping.json'}")
    print(f"- {MOCK_API_FIXTURES_DIR / 'settlements.json'}")
    print(f"- {MOCK_API_FIXTURES_DIR / 'accounts.json'}")
    print(f"- {LOG_FILE}")
    print(f"- {GENERATED_DIR / 'internal_payouts.json'}")
    print(f"- {GENERATED_DIR / 'seed_demo_data.sql'}")


if __name__ == "__main__":
    main()